table inet filter {
    chain input {
        type filter hook input priority filter; policy DROP;
        iif "lo" accept
        ct state established,related accept
        ip protocol icmp accept
        tcp dport 22 accept      # SSH administración
        tcp dport 5050 accept    # Servidor TCP principal
        tcp dport 8080 accept    # HTTP API principal
        tcp dport 9000 accept    # HAProxy TCP
        tcp dport 5051 accept    # Servidor TCP respaldo
        tcp dport 8081 accept    # HTTP API respaldo
        tcp dport 7070 accept    # Dashboard web
        log prefix "[NFT DROP] " drop
    }
    chain forward { policy drop; }
    chain output  { policy accept; }
}
